# Generated by Django 5.0.7 on 2024-07-15 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_studentattendance_remove_student_parents_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='student_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programmes.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmark',
            name='student_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programmes.student'),
            preserve_default=False,
        ),
    ]
