# Generated by Django 5.0.7 on 2024-07-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0003_studentattendance_student_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='studentmark',
            name='student_key',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_mark',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
        migrations.DeleteModel(
            name='StudentMark',
        ),
    ]
