# Generated by Django 5.0.7 on 2024-07-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0005_alter_student_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance',
            field=models.CharField(max_length=20),
        ),
    ]
