# Generated by Django 5.0.7 on 2024-07-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0008_remove_student_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='lecturer',
        ),
        migrations.AddField(
            model_name='student',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='student_mark',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudentAttendance',
        ),
        migrations.DeleteModel(
            name='StudentMark',
        ),
    ]
