# Generated by Django 5.0.7 on 2024-07-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0009_remove_studentmark_student_remove_programme_lecturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='level',
            field=models.IntegerField(),
        ),
    ]
